/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacio;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author bernat
 */
public class gestio_privilegiat extends javax.swing.JFrame {

    /**
     * Creates new form gestio_privilegiat
     */
    private int i = 0;
    private ctr_usuari_presentacio ctr_pres;
    public gestio_privilegiat(ctr_usuari_presentacio ctr) {
        initComponents();
        ctr_pres = ctr;
        introduir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Bernat Diaz
    private void initComponents() {
        crear = new JButton();
        modificar = new JButton();
        borrar = new JButton();
        privilegis = new JButton();
        informacio = new JButton();
        introduir = new JTextField();
        jScrollPane1 = new JScrollPane();
        taula = new JTable();
        resposta = new JLabel();
        sortir = new JButton();
        back = new JButton();
        jButton3 = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        Container contentPane = getContentPane();

        //---- crear ----
        crear.setText("crear usuari");
        crear.addActionListener(e -> crearActionPerformed(e));

        //---- modificar ----
        modificar.setText("modificar usuari");
        modificar.addActionListener(e -> modificarActionPerformed(e));

        //---- borrar ----
        borrar.setText("esborrar usuari");
        borrar.addActionListener(e -> borrarActionPerformed(e));

        //---- privilegis ----
        privilegis.setText("donar privilegis");
        privilegis.addActionListener(e -> privilegisActionPerformed(e));

        //---- informacio ----
        informacio.setText("informacio usuaris");
        informacio.addActionListener(e -> informacioActionPerformed(e));

        //======== jScrollPane1 ========
        {

            //---- taula ----
            taula.setModel(new DefaultTableModel(
                new Object[][] {
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                    {null, null, null, null, null, null},
                },
                new String[] {
                    "username", "password", "nom", "sexe", "data", "tipus"
                }
            ) {
                Class<?>[] columnTypes = new Class<?>[] {
                    String.class, String.class, String.class, String.class, String.class, String.class
                };
                boolean[] columnEditable = new boolean[] {
                    false, false, false, false, false, false
                };
                @Override
                public Class<?> getColumnClass(int columnIndex) {
                    return columnTypes[columnIndex];
                }
                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return columnEditable[columnIndex];
                }
            });
            jScrollPane1.setViewportView(taula);
        }

        //---- sortir ----
        sortir.setText("Sortir");
        sortir.addActionListener(e -> sortirActionPerformed(e));

        //---- back ----
        back.setText("Gestio usuari");
        back.addActionListener(e -> backActionPerformed(e));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(informacio, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(privilegis, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(borrar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modificar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(crear, GroupLayout.PREFERRED_SIZE, 119, GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(back)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(sortir))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addComponent(introduir, GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addComponent(resposta, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                    .addGap(38, 38, 38))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(crear)
                        .addComponent(sortir)
                        .addComponent(back))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(modificar)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(borrar)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(privilegis)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(informacio)
                            .addGap(26, 26, 26)
                            .addComponent(introduir, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(resposta)
                            .addGap(0, 21, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)))
        );
        pack();
        setLocationRelativeTo(getOwner());

        //---- jButton3 ----
        jButton3.setText("jButton3");
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        setVisible(false);
        ctr_pres.crear_usuari();
    }//GEN-LAST:event_crearActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        setVisible(false);
        ctr_pres.modificar_usuari_privilegiat();
    }//GEN-LAST:event_modificarActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        introduir.setVisible(true);
        resposta.setText("Introdueix el nom de l'usuari");
        if(!introduir.getText().equals("")){
            if(ctr_pres.borrar_usuari(introduir.getText())){
                resposta.setText("Usuari esborrat");
                introduir.setVisible(false);
                if(introduir.getText().equals(ctr_pres.usuari_actual())){
                    setVisible(false);
                    ctr_pres.inici();
                }
            }
            else resposta.setText("L'usuari no existia");
            introduir.setText("");
        }
    }//GEN-LAST:event_borrarActionPerformed

    private void privilegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privilegisActionPerformed
        introduir.setVisible(true);
        resposta.setText("Introdueix el nom de l'usuari");
        if(!introduir.getText().equals("")) {
            if(ctr_pres.donar_privilegis(introduir.getText())){
                resposta.setText("L'usuari ara és privilegiat");
                introduir.setVisible(false);
            }
            else resposta.setText("L'usuari no existia o ja era privilegiat");
            introduir.setText("");
        }
    }//GEN-LAST:event_privilegisActionPerformed

    private void informacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacioActionPerformed
        ArrayList<ArrayList<String>> users = ctr_pres.informacio_usuaris();
        DefaultTableModel model = (DefaultTableModel) taula.getModel();
        for(i = i; i >= 0; --i){
            model.removeRow(i);
        }
        for(i = 0;i < users.size(); ++i){
            ArrayList<String> aux = users.get(i);
            model.insertRow(0, aux.toArray());
        }
    }//GEN-LAST:event_informacioActionPerformed

    private void sortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortirActionPerformed
        setVisible(false);
        ctr_pres.inici();
    }//GEN-LAST:event_sortirActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
        ctr_pres.gestio_usuari();
    }//GEN-LAST:event_backActionPerformed
    /**
     * @param args the command line arguments
     */
    public void vista() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestio_privilegiat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestio_privilegiat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestio_privilegiat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestio_privilegiat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestio_privilegiat(ctr_pres).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Bernat Diaz
    private JButton crear;
    private JButton modificar;
    private JButton borrar;
    private JButton privilegis;
    private JButton informacio;
    private JTextField introduir;
    private JScrollPane jScrollPane1;
    private JTable taula;
    private JLabel resposta;
    private JButton sortir;
    private JButton back;
    private JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
