/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacio;

import java.awt.*;
import java.awt.event.*;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

/**
 *
 * @author bernat
 */
public class inici extends javax.swing.JFrame {

    /**
     * Creates new form inici
     */
    private ctr_usuari_presentacio ctr_pres;
    private void ImportarDadesActionPerformed(ActionEvent e) {
        if(ctr_pres.cargar_graf()) error.setText("Dades carregades");
        else error.setText("No es troben els fitxers de dades");
    }

    private void importarActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void guardarActionPerformed(ActionEvent e) {
        // TODO add your code here
    }

    private void GuardarDadesActionPerformed(ActionEvent e) {
        try {
            if (ctr_pres.guardar_graf()) error.setText("Dades guardades");
            else error.setText("No hi ha dades");
        }
        catch(IOException e2) {
            error.setText("No es troben els fitxers de dades");
        }
    }

    public inici(ctr_usuari_presentacio ctr) {
        initComponents();
        ctr_pres = ctr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Bernat Diaz
    private void initComponents() {
        log = new JButton();
        importarUsuaris = new JButton();
        guardarUsuaris = new JButton();
        error = new JLabel();
        resposta = new JLabel();
        ImportarDades = new JButton();
        GuardarDades = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        Container contentPane = getContentPane();

        //---- log ----
        log.setText("Loggin");
        log.addActionListener(e -> logActionPerformed(e));

        //---- importarUsuaris ----
        importarUsuaris.setText("Importar usuaris");
        importarUsuaris.addActionListener(e -> {
			importarActionPerformed(e);
			importarUsuarisActionPerformed(e);
		});

        //---- guardarUsuaris ----
        guardarUsuaris.setText("Guardar usuaris");
        guardarUsuaris.addActionListener(e -> {
			guardarActionPerformed(e);
			guardarUsuarisActionPerformed(e);
		});

        //---- ImportarDades ----
        ImportarDades.setText("Importar dades");
        ImportarDades.addActionListener(e -> ImportarDadesActionPerformed(e));

        //---- GuardarDades ----
        GuardarDades.setText("Guardar dades");
        GuardarDades.addActionListener(e -> GuardarDadesActionPerformed(e));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(145, 145, 145)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addComponent(GuardarDades, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ImportarDades, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resposta, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardarUsuaris, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(importarUsuaris, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(log, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(error)
                    .addContainerGap(111, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(error))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(log)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(importarUsuaris)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(guardarUsuaris)))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ImportarDades)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(GuardarDades)
                    .addGap(88, 88, 88)
                    .addComponent(resposta)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        setVisible(false);
        ctr_pres.loggin();
    }//GEN-LAST:event_logActionPerformed

    private void importarUsuarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarActionPerformed
        try{
            ctr_pres.carregar_usuaris();
            error.setText("Usuaris carregats");
        }
        catch(IndexOutOfBoundsException e){
            error.setText("Fitxer corrumput");
        }
        catch(FileNotFoundException|NullPointerException e){
            error.setText("No es troba el fitxer");
        }
    }//GEN-LAST:event_importarActionPerformed

    private void guardarUsuarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        try{
            ctr_pres.guardar_usuaris();
            error.setText("Usuaris guardats");
        }
        catch(FileNotFoundException|NullPointerException e){
            error.setText("No es troba el fitxer");
        }
    }//GEN-LAST:event_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void vista() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inici(ctr_pres).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Bernat Diaz
    private JButton log;
    private JButton importarUsuaris;
    private JButton guardarUsuaris;
    private JLabel error;
    private JLabel resposta;
    private JButton ImportarDades;
    private JButton GuardarDades;
    // End of variables declaration//GEN-END:variables
}
